# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainform.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.data_menu = QtWidgets.QMenu(self.menubar)
        self.data_menu.setObjectName("data_menu")
        self.calc_menu = QtWidgets.QMenu(self.menubar)
        self.calc_menu.setObjectName("calc_menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_new_project = QtWidgets.QAction(MainWindow)
        self.action_new_project.setObjectName("action_new_project")
        self.action_open_project = QtWidgets.QAction(MainWindow)
        self.action_open_project.setObjectName("action_open_project")
        self.action_delete_project = QtWidgets.QAction(MainWindow)
        self.action_delete_project.setObjectName("action_delete_project")
        self.action_import_coords_plast = QtWidgets.QAction(MainWindow)
        self.action_import_coords_plast.setObjectName("action_import_coords_plast")
        self.action_import_MER = QtWidgets.QAction(MainWindow)
        self.action_import_MER.setObjectName("action_import_MER")
        self.action_import_wells = QtWidgets.QAction(MainWindow)
        self.action_import_wells.setObjectName("action_import_wells")
        self.action_export_table_result_wells_candidates = QtWidgets.QAction(MainWindow)
        self.action_export_table_result_wells_candidates.setObjectName("action_export_table_result_wells_candidates")
        self.action_export_voronoi_polygons = QtWidgets.QAction(MainWindow)
        self.action_export_voronoi_polygons.setObjectName("action_export_voronoi_polygons")
        self.action_export_graphics_debits = QtWidgets.QAction(MainWindow)
        self.action_export_graphics_debits.setObjectName("action_export_graphics_debits")
        self.action_save_project = QtWidgets.QAction(MainWindow)
        self.action_save_project.setObjectName("action_save_project")
        self.action_close_project = QtWidgets.QAction(MainWindow)
        self.action_close_project.setObjectName("action_close_project")
        self.take_data = QtWidgets.QAction(MainWindow)
        self.take_data.setObjectName("take_data")
        self.calc = QtWidgets.QAction(MainWindow)
        self.calc.setObjectName("calc")
        self.calc_action = QtWidgets.QAction(MainWindow)
        self.calc_action.setObjectName("calc_action")
        self.data_menu.addAction(self.take_data)
        self.calc_menu.addAction(self.calc_action)
        self.menubar.addAction(self.data_menu.menuAction())
        self.menubar.addAction(self.calc_menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.data_menu.setTitle(_translate("MainWindow", "Данные"))
        self.calc_menu.setTitle(_translate("MainWindow", "Расчеты"))
        self.action_new_project.setText(_translate("MainWindow", "Создать проект"))
        self.action_open_project.setText(_translate("MainWindow", "Открыть проект"))
        self.action_delete_project.setText(_translate("MainWindow", "Удалить проект"))
        self.action_import_coords_plast.setText(_translate("MainWindow", "Координаты пластопересечений"))
        self.action_import_MER.setText(_translate("MainWindow", "МЭР"))
        self.action_import_wells.setText(_translate("MainWindow", "Фонд скважин"))
        self.action_export_table_result_wells_candidates.setText(_translate("MainWindow", "Таблица с результатами подбора скважин-кандидатов"))
        self.action_export_voronoi_polygons.setText(_translate("MainWindow", "Полигоны Вороного"))
        self.action_export_graphics_debits.setText(_translate("MainWindow", "Графики дебитов окружающих скважин"))
        self.action_save_project.setText(_translate("MainWindow", "Сохранить проект"))
        self.action_close_project.setText(_translate("MainWindow", "Закрыть проект"))
        self.take_data.setText(_translate("MainWindow", "Импорт данных"))
        self.calc.setText(_translate("MainWindow", "Расчет"))
        self.calc_action.setText(_translate("MainWindow", "Запуск расчетов"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
